steps:

- name: us-central1-docker.pkg.dev/kcc-clean/docker-repo/k8s-cost-estimator:v0.0.1
  entrypoint: 'bash'
  args: 
    - '-c'
    - |
      set -e

      echo ""
      echo "*************************************************************************"
      echo "** Checking out 'main' branch ..."
      echo "*************************************************************************"
      rm -rf previous
      git config --global user.email "ramneekkhurana@google.com" && git config --global user.name "ramneekkh"
      git clone https://github.com/ramneekkh/k8s-cost-estimator-github.git previous/
      cd previous
      git checkout main 
      cd ..

      echo ""
      echo "*************************************************************************"
      echo "** Estimating cost difference between current and previous versions..."
      echo "*************************************************************************"
      k8s-cost-estimator --k8s wordpress --k8s-prev previous/wordpress --output output.json --environ=GITHUB
